server:
  port: 9000

spring:
  cloud:
    gateway:
      # 网关全局跨域配置
      globalcors:
        cors-configurations:
          '[/**]':
            allowedOrigins: "http://localhost:9527"
            allowedMethods: "*"
            allowedHeaders: "*"
            allowCredentials: true
        # 解决options请求被拦截的问题
        add-to-simple-url-handler-mapping: true

      routes:
        - id: loginModule
          uri: http://localhost:8083
          predicates:
            - Path=/LoginModule/**
          filters:
            - StripPrefix=1

        - id: userMgmt
          uri: http://localhost:8081
          predicates:
            - Path=/UserMgmt/**
          filters:
            - StripPrefix=1

        - id: workflowMgmt
          uri: http://localhost:8084
          predicates:
            - Path=/WorkflowMgmt/**
          filters:
            - StripPrefix=1